<?php

// SPDX-FileCopyrightText: 2026 Adam Dean
// SPDX-License-Identifier: Apache-2.0

namespace Cardano\Transaction\Tests;

use Cardano\Transaction\Address\Credential;
use Cardano\Transaction\Address\Network;
use Cardano\Transaction\Address\RewardAddress;
use Cardano\Transaction\Cbor\CborCodec;
use Cardano\Transaction\Exception\ScriptException;
use Cardano\Transaction\Primitives\WitnessSet;
use Cardano\Transaction\Script\NativeScript;
use PHPUnit\Framework\Attributes\DataProviderExternal;
use PHPUnit\Framework\TestCase;

/**
 * This package against an independent conformance corpus.
 *
 * The corpus was generated by another implementation, in another language, from a written specification. Every value
 * in it -- the CBOR, the script hash, the addresses, and the answer for each witness set -- was computed there and
 * not here, so reproducing one is evidence rather than a restatement. The ten recorded mainnet scripts in
 * NativeScriptCorpusTest prove the encoder against the chain at ten points; this proves it against 109 generated
 * shapes chosen to sit on the edges the chain's own scripts never reach.
 *
 * What this suite does not check is as load-bearing as what it does, and it is checked too:
 *
 *   - Seventeen vectors hold shapes this package refuses to build. They are listed in ArachneCorpus and asserted as
 *     refusals, so the boundary is a fact in the suite rather than an absence.
 *   - Every vector records governance identifiers in two standards. This package has no governance credential, so
 *     nothing here reads them.
 *   - Fifteen vectors have two valid script hashes because a container holds twenty-four or more sub-scripts. This
 *     package writes the definite-length form, which is the one the JavaScript ecosystem writes and is not the one
 *     cardano-cli writes. The tests below say which side each surface of the package is on.
 */
class ArachneConformanceTest extends TestCase
{
    /**
     * The three networks a vector records addresses for. Preview and preprod share network tag 0, so a script has one
     * address valid on both, and the corpus records the same string twice for that reason.
     */
    private const NETWORKS = ['mainnet', 'preview', 'preprod'];

    // ------------------------------------------------------------------ encoding

    #[DataProviderExternal(ArachneCorpus::class, 'buildableVectors')]
    public function test_a_vector_encodes_to_the_bytes_the_corpus_recorded(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $script = NativeScript::fromArray($vector['script']);
        $definite = $vector['encoding']['definite'];

        $this->assertSame($definite['cborHex'], $script->cborHex(), $id);
        $this->assertSame($definite['preimageHex'], bin2hex("\x00".$script->cbor()), $id.' preimage');
        $this->assertSame($definite['cborBytes'], strlen($script->cbor()), $id.' byte count');
    }

    /**
     * The hash, and the two places the package hands the same 28 bytes out under another name.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'buildableVectors')]
    public function test_a_vector_hashes_to_the_script_hash_the_corpus_recorded(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $script = NativeScript::fromArray($vector['script']);
        $expected = $vector['encoding']['definite']['scriptHash'];

        $this->assertSame($expected, $script->hashHex(), $id);
        $this->assertSame($expected, $script->policyId(), $id.' policy id');
        $this->assertSame($expected, $script->credential()->hex(), $id.' credential');
        $this->assertTrue($script->credential()->isScript(), $id.' credential kind');
    }

    /**
     * Every address the corpus records for a script hash, on every network it records one for.
     *
     * A script hash is one credential in several envelopes, and each envelope has its own header byte. An
     * implementation that had the hash right and the header wrong would pass every assertion above and still send
     * funds to an address nobody controls.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'buildableVectors')]
    public function test_a_vector_pays_to_the_addresses_the_corpus_recorded(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $script = NativeScript::fromArray($vector['script']);
        $credentials = $vector['credentials']['definite'];
        $scriptCredential = $script->credential();

        foreach (self::NETWORKS as $name) {
            $network = Network::named($name);

            $this->assertSame(
                $credentials['enterprise'][$name],
                $script->enterpriseAddress($network)->toBech32(),
                $id.' enterprise on '.$name
            );

            // The corpus's base address carries the script in both slots, so the delegation credential is the script's
            // own hash under a script kind rather than a stake key's.
            $this->assertSame(
                $credentials['baseScriptStake'][$name],
                $script->baseAddress($network, $scriptCredential)->toBech32(),
                $id.' base address on '.$name
            );

            $this->assertSame(
                $credentials['reward'][$name],
                RewardAddress::of($network, $scriptCredential)->toBech32(),
                $id.' reward address on '.$name
            );
        }
    }

    /**
     * The bytes read back. A script reaches this package as CBOR far more often than as JSON, and a decoder that
     * disagreed with the encoder about any of it would show up here rather than the first time a script was spent.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'buildableVectors')]
    public function test_a_vector_survives_a_round_trip_through_its_own_bytes(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $definite = $vector['encoding']['definite'];

        $decoded = NativeScript::fromCbor((string) hex2bin($definite['cborHex']));

        $this->assertSame($definite['cborHex'], $decoded->cborHex(), $id);
        $this->assertSame($definite['scriptHash'], $decoded->hashHex(), $id.' hash');
        $this->assertSame(
            self::orderedByKey($vector['script']),
            self::orderedByKey($decoded->toArray()),
            $id.' structure'
        );
    }

    /**
     * The key hashes the script names, against the corpus's own count of them.
     *
     * A vector records how many `sig` clauses it holds and which distinct key hashes appear in them, and the two
     * differ whenever a hash is named twice. That difference is the whole content of the duplicate-keys family, and an
     * implementation that collected key hashes into a set somewhere would lose it here rather than in a threshold
     * nobody could satisfy.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'buildableVectors')]
    public function test_a_vector_names_the_key_hashes_the_corpus_counted(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $named = NativeScript::fromArray($vector['script'])->keyHashes();

        $this->assertCount($vector['shape']['sigCount'], $named, $id.' sig count');

        $distinct = array_values(array_unique($named));
        $expected = $vector['shape']['keyHashes'];
        sort($distinct);
        sort($expected);

        $this->assertSame($expected, $distinct, $id.' key hashes');
    }

    // -------------------------------------------------------------- satisfaction

    /**
     * Whether a witness set satisfies the script, for every case the corpus sampled.
     *
     * The expectations are the ledger's `evalTimelock` transcribed, and the sampling walks the cases that separate a
     * correct evaluator from a plausible one: a threshold counts satisfied sub-scripts rather than distinct keys, a
     * nested container is one vote in its parent whatever it holds, and a timelock against an absent interval bound
     * fails rather than being skipped.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'buildableVectors')]
    public function test_a_vector_agrees_about_every_witness_set_the_corpus_sampled(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $script = NativeScript::fromArray($vector['script']);

        $this->assertNotEmpty($vector['satisfaction'], $id.' records no satisfaction case.');

        foreach ($vector['satisfaction'] as $case) {
            $this->assertSame(
                $case['expected'],
                $script->isSatisfiedBy(
                    $case['signers'],
                    $case['validityStart'] ?? null,
                    $case['validityEnd'] ?? null,
                ),
                $id.' case '.$case['id'].': '.$case['expectedReason']
            );
        }
    }

    /**
     * The count, so that a corpus refreshed into a smaller sample cannot quietly reduce what this suite proves.
     */
    public function test_the_suite_evaluates_every_satisfaction_case_of_every_vector_it_can_build(): void
    {
        $checked = 0;
        $skipped = 0;

        foreach (ArachneCorpus::ids() as $id) {
            $count = count(ArachneCorpus::vector($id)['satisfaction']);

            if (isset(ArachneCorpus::refused()[$id])) {
                $skipped += $count;

                continue;
            }

            $checked += $count;
        }

        $this->assertSame(952, $checked, 'The number of witness sets this suite evaluates has moved.');
        $this->assertSame(115, $skipped, 'The number of witness sets this suite cannot reach has moved.');
        $this->assertSame(
            $checked + $skipped,
            ArachneCorpus::index()['satisfactionCaseCount'],
            'The corpus holds cases that are neither evaluated nor accounted for.'
        );
    }

    // ------------------------------------------------------- the two framings

    /**
     * A container of twenty-four or more sub-scripts has two valid encodings and therefore two valid script hashes.
     *
     * cardano-binary, which is what cardano-node and cardano-cli serialize through, writes a definite-length array up
     * to twenty-three elements and an indefinite-length array from twenty-four. cardano-serialization-lib, MeshJS and
     * this package write a definite-length array at every size. Both are well-formed, the ledger accepts both, and it
     * hashes whichever bytes it received.
     *
     * This asserts which side this package's JSON path is on, which is the definite one. A caller holding the JSON of
     * a wide script that cardano-cli built gets a different address here than cardano-cli gives, and nothing about
     * either result is malformed.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'encodingSensitiveVectors')]
    public function test_a_wide_container_is_written_in_the_definite_form(string $id): void
    {
        $vector = ArachneCorpus::vector($id);
        $script = NativeScript::fromArray($vector['script']);
        $definite = $vector['encoding']['definite'];
        $cardanoBinary = $vector['encoding']['cardanoBinary'];

        $this->assertNotSame(
            $definite['cborHex'],
            $cardanoBinary['cborHex'],
            $id.' is listed as encoding sensitive but the corpus records one encoding twice.'
        );
        $this->assertSame($definite['cborHex'], $script->cborHex(), $id);
        $this->assertSame($definite['scriptHash'], $script->hashHex(), $id);
        $this->assertNotSame($cardanoBinary['scriptHash'], $script->hashHex(), $id.' second hash');
    }

    /**
     * The other framing, arriving as bytes rather than as JSON.
     *
     * NativeScript::fromCbor refuses it, because re-encoding it here would produce the definite bytes and therefore a
     * hash that is not the one the ledger assigned. The refusal is the correct answer for a model that re-encodes what
     * it decoded, and it is only safe because the package has another path for these bytes.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'encodingSensitiveVectors')]
    public function test_the_framing_a_node_writes_is_refused_rather_than_re_encoded(string $id): void
    {
        $bytes = (string) hex2bin(ArachneCorpus::vector($id)['encoding']['cardanoBinary']['cborHex']);

        $this->expectException(ScriptException::class);
        $this->expectExceptionMessage('canonical');

        NativeScript::fromCbor($bytes);
    }

    /**
     * That other path, which is the one a transaction actually takes.
     *
     * A witness set hashes the bytes each script arrived in and never rebuilds them, so a script cardano-cli wrote is
     * hashed to the hash cardano-cli published even though this package would have written those bytes differently.
     * This is the assertion that says the divergence costs nothing when a script is read from a transaction, and
     * everything when one is rebuilt from JSON.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'encodingSensitiveVectors')]
    public function test_a_witness_set_hashes_the_bytes_the_script_arrived_in(string $id): void
    {
        $cardanoBinary = ArachneCorpus::vector($id)['encoding']['cardanoBinary'];
        $bytes = (string) hex2bin($cardanoBinary['cborHex']);

        // A witness set carrying one native script and nothing else: {1: [script]}.
        $witnessSet = WitnessSet::fromCbor(CborCodec::decode((string) hex2bin('a10181'.$cardanoBinary['cborHex'])));

        $this->assertSame([$bytes], $witnessSet->nativeScriptBytes(), $id.' bytes');
        $this->assertSame(
            [$cardanoBinary['scriptHash']],
            array_map(bin2hex(...), $witnessSet->nativeScriptHashes()),
            $id.' hash'
        );
    }

    /**
     * Below twenty-four the question does not arise, and the corpus says so for every other vector.
     */
    public function test_a_narrow_script_has_one_encoding_and_one_hash(): void
    {
        $sensitive = 0;

        foreach (ArachneCorpus::ids() as $id) {
            $encoding = ArachneCorpus::vector($id)['encoding'];

            if ($encoding['encodingSensitive'] === true) {
                $sensitive++;

                continue;
            }

            $this->assertSame(
                $encoding['definite']['cborHex'],
                $encoding['cardanoBinary']['cborHex'],
                $id.' is not marked encoding sensitive but the two encodings differ.'
            );
            $this->assertSame(
                $encoding['definite']['scriptHash'],
                $encoding['cardanoBinary']['scriptHash'],
                $id.' has two hashes without being marked encoding sensitive.'
            );
        }

        $this->assertSame(15, $sensitive, 'The number of encoding sensitive vectors has moved.');
        $this->assertSame($sensitive, ArachneCorpus::index()['encodingSensitiveCount']);
    }

    // ------------------------------------------------------ what is not covered

    /**
     * The shapes this package will not build, each refused for the reason the manifest records.
     *
     * The grammar admits every one of them: `script_all = (1, [* native_script])` is zero or more, and `n` in
     * `script_n_of_k = (3, n : int64, [* native_script])` is a signed 64-bit integer. They hash to real script hashes
     * that sit at real addresses, and one of them has been on mainnet since epoch 392.
     */
    #[DataProviderExternal(ArachneCorpus::class, 'refusedVectors')]
    public function test_a_shape_this_package_will_not_build_is_refused_and_not_mangled(string $id, string $gap): void
    {
        $vector = ArachneCorpus::vector($id);

        try {
            NativeScript::fromArray($vector['script']);
            $this->fail($id.' is listed as refused and was built. The list in ArachneCorpus is out of date.');
        } catch (ScriptException $e) {
            $this->assertNotSame('', $e->getMessage(), $id.' was refused without saying why.');
        }

        // The same shape arriving as bytes rather than as JSON is refused on the same ground rather than decoded.
        try {
            NativeScript::fromCbor((string) hex2bin($vector['encoding']['definite']['cborHex']));
            $this->fail($id.' is refused as JSON and accepted as CBOR.');
        } catch (ScriptException $e) {
            $this->assertNotSame('', $e->getMessage(), $id.' CBOR was refused without saying why.');
        }

        $this->assertContains($gap, [
            ArachneCorpus::GAP_EMPTY_CONTAINER,
            ArachneCorpus::GAP_THRESHOLD_AT_OR_BELOW_ZERO,
            ArachneCorpus::GAP_THRESHOLD_ABOVE_CHILD_COUNT,
        ], $id.' is refused for a shape the manifest does not name.');
    }

    /**
     * The refusals are about what this package will build, not about bytes it gets wrong.
     *
     * Every refused vector has one encoding and one hash, so there is no disagreement underneath the refusal: the
     * corpus and this package would agree about the bytes if the model could hold the shape at all.
     */
    public function test_a_refused_shape_is_a_shape_this_package_cannot_hold_rather_than_bytes_it_disputes(): void
    {
        foreach (ArachneCorpus::refused() as $id => $gap) {
            $encoding = ArachneCorpus::vector($id)['encoding'];

            $this->assertFalse($encoding['encodingSensitive'], $id);
            $this->assertMatchesRegularExpression('/^[0-9a-f]{56}$/', $encoding['definite']['scriptHash'], $id);
        }

        $this->assertCount(17, ArachneCorpus::refused());
        $this->assertCount(109, ArachneCorpus::buildable());
        $this->assertCount(126, ArachneCorpus::ids());
    }

    /**
     * Every vector is either checked or recorded as unreachable. There is no third state, and a vector added to the
     * corpus by a refresh cannot land in one.
     */
    public function test_every_vector_is_either_checked_or_listed_as_refused(): void
    {
        $accounted = array_merge(ArachneCorpus::buildable(), array_keys(ArachneCorpus::refused()));
        $ids = ArachneCorpus::ids();

        sort($accounted);
        sort($ids);

        $this->assertSame($ids, $accounted);

        foreach (array_keys(ArachneCorpus::refused()) as $id) {
            $this->assertContains($id, $ids, $id.' is listed as refused and is not in the corpus.');
        }
    }

    /**
     * The refusal list against the corpus's own record of which vectors are unusual and why.
     *
     * The list is written out in ArachneCorpus so that a reader can see it, and it has to be exactly the set of
     * vectors the corpus itself marked as an empty container or an out-of-range threshold. Deriving it a second way
     * and comparing is what stops the list from becoming a place to hide a vector that started failing.
     */
    public function test_the_refusal_list_is_the_set_of_shapes_the_corpus_marked(): void
    {
        $listed = ArachneCorpus::refused();
        $derived = ArachneCorpus::refusedByRemark();

        ksort($listed);
        ksort($derived);

        $this->assertSame($derived, $listed);

        $counts = array_count_values($listed);
        $expected = [
            ArachneCorpus::GAP_EMPTY_CONTAINER => 3,
            ArachneCorpus::GAP_THRESHOLD_AT_OR_BELOW_ZERO => 7,
            ArachneCorpus::GAP_THRESHOLD_ABOVE_CHILD_COUNT => 7,
        ];
        ksort($counts);
        ksort($expected);

        $this->assertSame($expected, $counts, 'The shapes this package cannot build have moved.');
    }

    /**
     * The credential roles a vector records, against the roles this package can derive.
     *
     * Governance identifiers are recorded for every vector under both CIP-129 and CIP-105. Nothing in this package
     * reads them, because it has no governance credential type, and this is where that is written down.
     */
    public function test_the_corpus_records_one_credential_role_this_package_cannot_derive(): void
    {
        $roles = array_keys(ArachneCorpus::vector(ArachneCorpus::buildable()[0])['credentials']['definite']);

        $this->assertSame(ArachneCorpus::ROLES_RECORDED, $roles);
        $this->assertSame(
            ['governance'],
            array_values(array_diff(ArachneCorpus::ROLES_RECORDED, ArachneCorpus::ROLES_CHECKED)),
            'The roles this suite checks and the roles the corpus records have drifted apart.'
        );

        // And the shape of what is not checked, so a reader knows what would have to be built to check it.
        $governance = ArachneCorpus::vector(ArachneCorpus::buildable()[0])['credentials']['definite']['governance'];

        $this->assertSame(['drep', 'ccCold', 'ccHot'], array_keys($governance));
        $this->assertSame(['cip129', 'cip105'], array_keys($governance['drep']));
    }

    /**
     * Preview and preprod share network tag 0, so one address is valid on both. The package has one testnet, and this
     * is the assertion that says the corpus agrees rather than that the two strings were copied.
     */
    public function test_one_testnet_address_serves_both_testnets(): void
    {
        foreach (ArachneCorpus::buildable() as $id) {
            $credentials = ArachneCorpus::vector($id)['credentials']['definite'];

            foreach (ArachneCorpus::ROLES_CHECKED as $role) {
                $this->assertSame($credentials[$role]['preview'], $credentials[$role]['preprod'], $id.' '.$role);
                $this->assertNotSame($credentials[$role]['mainnet'], $credentials[$role]['preview'], $id.' '.$role);
            }
        }
    }

    /**
     * The same script with the fields of each clause in a fixed order, so that a comparison of two structures is not
     * a comparison of two key orders. The list under `scripts` is left alone, because the order of the sub-scripts is
     * part of what a script says and moving one moves the hash.
     *
     * @param  array<string, mixed>  $script
     * @return array<string, mixed>
     */
    private static function orderedByKey(array $script): array
    {
        ksort($script);

        if (isset($script['scripts'])) {
            $script['scripts'] = array_map(self::orderedByKey(...), $script['scripts']);
        }

        return $script;
    }
}
